CREATE TABLE teams (
	id SERIAL PRIMARY KEY NOT NULL,
	name TEXT UNIQUE NOT NULL
);

CREATE TABLE team_members (
	id SERIAL PRIMARY KEY NOT NULL,
	team_id INTEGER NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
	user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX idx_teams_name ON teams(name);
