
INSERT INTO users (id, username, team_name, is_active) VALUES
('u1','alice','backend', true),
('u2','bob','backend', true),
('u3','carol','frontend', true),
('u4','dave','frontend', false),
('u5','eve','payments', true),
('u6','frank','devops', true),
('u7','grace','qa', true),
('u8','heidi','mobile', true),
('u9','ivan','data', true),
('u10','judy','security', true),
('u11','kim','support', true),
('u12','leo','marketing', true),
('u13','mallory','analytics', true),
('u14','nancy','design', true),
('u15','oscar','infrastructure', true),
('u16','peggy','ops', true),
('u17','quentin','research', true),
('u18','rachel','sales', true),
('u19','sybil','legal', true),
('u20','trent','hr', true),
('u21','uma','customer_success', true),
('u22','victor','product', true),
('u23','wendy','backend', true),
('u24','xander','frontend', true),
('u25','yvonne','payments', true),
('u26','zack','qa', true);
